language: node_js

node_js:
  - '8'

script:
  - npm run packagr

before_deploy:
  - cd dist

deploy:
  provider: npm
  email: smnbbrv@npmjs.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
