language: node_js

node_js:
  - '8'

script:
  - npm run packagr

before_deploy:
  - cd dist

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key:
    secure: $NPM_TOKEN
  skip_cleanup: true
  on:
    repo: smnbbrv/ngx-mat-codemirror
    branch: master
    tags: true
